[tox]
envlist = py313

[testenv]
install_command = pip install -U {opts} {packages}
deps =
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
setenv =
  TESTING=TRUE
  PASTEFILE_SETTINGS={toxinidir}/pastefile-test.cfg
commands =
    pytest -v {posargs}
    flake8 --max-line-length=100 pastefile
